import "./../libs/libs.js";
import { toToggleMenu } from "./modules/menu-burger.js";
import { initTarifsTabs } from "./modules/tabs.js";
import { initSwiper } from "./modules/swiper.js";
import { initCost } from "./modules/cost.js";
import { addHeadingAnimation } from "./modules/heading.js";
import { initSubHeadingAnimation } from "./modules/sub-heading-animation.js";
import { initIHereAnimation } from "./modules/ihere-animation.js";
import { initTitleAnimation } from "./modules/title-animation.js";
// import { myCaptcha } from "./modules/captcha.js";

initTitleAnimation();
initIHereAnimation();
toToggleMenu();
initTarifsTabs();
initSwiper();
initCost();
addHeadingAnimation();
initSubHeadingAnimation();
// myCaptcha();
